# Generated by Django 5.0.2 on 2024-02-28 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        ('users', '0003_alter_user_portfolio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='Срок')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED'), ('DISPUTED', 'DISPUTED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=100, verbose_name='Статус')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_deals', to='users.user', verbose_name='Покупатель')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_deals', to='users.user', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.order', verbose_name='Заказ')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Работник')),
            ],
        ),
    ]
