# Generated by Django 5.0.2 on 2024-02-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('portfolio_link', models.CharField(max_length=200, verbose_name='Ссылка на портфолио')),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('WORKER', 'WORKER'), ('CUSTOMER', 'CUSTOMER'), ('SUPPORT', 'SUPPORT')], default='CUSTOMER', max_length=100, verbose_name='Роль')),
            ],
        ),
    ]
