# Generated by Django 5.0.2 on 2024-02-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_portfolio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portfolio_link',
            field=models.CharField(max_length=200, verbose_name='Ссылка на портфолио'),
        ),
    ]
