# Generated by Django 5.0.2 on 2024-02-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_tag',
            field=models.CharField(default='', max_length=100, verbose_name='Тег'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='portfolio_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на портфолио'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='ID пользователя'),
        ),
    ]
