# Generated by Django 5.0.2 on 2024-05-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_image_id_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
