# Generated by Django 5.0.2 on 2024-05-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_id',
            field=models.CharField(default=0, max_length=128, verbose_name='Айди картинки в телеграм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image_id',
            field=models.CharField(default=0, max_length=128, verbose_name='Айди картинки в телеграм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
